// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (created_at, updated_at, title, post_url, post_description,
published_at, feed_id) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING post_id, created_at, updated_at, title, post_url, post_description, published_at, feed_id
`

type CreatePostParams struct {
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           sql.NullString
	PostUrl         string
	PostDescription sql.NullString
	PublishedAt     sql.NullTime
	FeedID          int32
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.PostUrl,
		arg.PostDescription,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.PostUrl,
		&i.PostDescription,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT post_id, posts.created_at, posts.updated_at, title, post_url,
post_description, published_at, posts.feed_id FROM posts
INNER JOIN feed_follows f ON (f.feed_id = posts.feed_id)
WHERE f.user_id = $1
ORDER BY published_at
LIMIT $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.PostUrl,
			&i.PostDescription,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
