-- +goose Up
CREATE TABLE posts (
    post_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    title TEXT,
    post_url TEXT UNIQUE NOT NULL,
    post_description TEXT,
    published_at TIMESTAMP,
    feed_id INTEGER NOT NULL,
    CONSTRAINT fk_feeds FOREIGN KEY (feed_id)
    REFERENCES feeds(id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- +goose Down
DROP TABLE posts;